# Generated by Django 5.1.7 on 2025-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rental_frequency',
            field=models.CharField(blank=True, choices=[('Month', 'Month'), ('Week', 'Week'), ('Day', 'Day')], max_length=20, null=True),
        ),
    ]
