# Generated by Django 5.1.7 on 2025-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_rental_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='borough',
            field=models.CharField(blank=True, choices=[('Camden', 'Camden'), ('Greenwich', 'Greenwich'), ('Hackney', 'Hackney'), ('Hammersmith and Fulham', 'Hammersmith and Fulham'), ('Islington', 'Islington'), ('Kensington and Chelsea', 'Kensington and Chelsea'), ('Lambeth', 'Lambeth'), ('Lewisham', 'Lewisham'), ('Southwark', 'Southwark'), ('Tower Hamlets', 'Tower Hamlets'), ('Wandsworth', 'Wandsworth'), ('Westminster', 'Westminster'), ('City of London', 'City of London'), ('Barking and Dangenham', 'Barking and Dangenham'), ('Barnet', 'Barnet'), ('Bexley', 'Bexley'), ('Brent', 'Brent'), ('Bromley', 'Bromley'), ('Croydon', 'Croydon'), ('Ealing', 'Ealing'), ('Enfield', 'Enfield'), ('Haringey', 'Haringey'), ('Harrow', 'Harrow'), ('Havering', 'Havering'), ('Hillingdon', 'Hillingdon'), ('Hounslow', 'Hounslow'), ('Kingston upon Thames', 'Kingston upon Thames'), ('Merton', 'Merton'), ('Newham', 'Newham'), ('Redbridge', 'Redbridge'), ('Richmond upon Thames', 'Richmond upon Thames'), ('Sutton', 'Sutton'), ('Waltham Forest', 'Waltham Forest')], max_length=50, null=True),
        ),
    ]
