# Generated by Django 5.1.7 on 2025-03-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_borough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='borough',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
