# Generated by Django 5.1.7 on 2025-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='seller',
        ),
    ]
